# Generated by Django 3.2.9 on 2021-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('NoteId', models.AutoField(primary_key=True, serialize=False)),
                ('NoteCont', models.CharField(max_length=1000)),
            ],
        ),
    ]
